version: '3.8'

services:
  php-apache:
    build: .
    container_name: expertCart-apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: expertCart-postgres
    environment:
      POSTGRES_DB: softMercado
      POSTGRES_USER: softMercado
      POSTGRES_PASSWORD: softmercado
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: expertCart-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
  frontend:
    image: node:16-alpine
    container_name: expertCart-react
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./expertCart-react:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - db
volumes:
  postgres_data:
